version: "3.3"
services:
  ui:
    image: bluebrain/bioexplorer-ui
    labels:
      description: Blue Brain BioExplorer User Interface
      name: Web User Interface
    ports:
      - "5002:8080"
  sdk:
    image: bluebrain/bioexplorer-python-sdk
    labels:
      description: Blue Brain BioExplorer Jupyter Notebooks
      name: Jupyter notebooks
    ports:
      - "5001:8888"
  api:
    image: bluebrain/bioexplorer
    labels:
      description: Blue Brain BioExplorer core API
      name: Core API
    ports:
      - "5000:8200"
