#!/bin/sh

jupyter-nbextension enable nglview --py --sys-prefix
jupyter notebook --allow-root --ip=0.0.0.0 --port=8888 --notebook-dir=/app/BioExplorer/notebooks --NotebookApp.token='' --NotebookApp.password=''
