on: [push]

jobs:
  bioexplorer_job:
    runs-on: ubuntu-latest
    name: BioExplorer
    steps:
    - name: Build python package
      run: >-
        cd bioexplorer/pythonsdk
        virtualenv -p python3 env
        source env/bin/activate
        pip install -r requirements_dev.txt
        python setup.py install
    - name: Publish to PyPI (test)
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TEST_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
    - uses: actions/checkout@v2
      name: Check out code
    - name: Login to DockerHub
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Back-end
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/bioexplorer:latest
    - name: Build and push Python SDK
      uses: docker/build-push-action@v2
      with:
        context: ./bioexplorer/pythonsdk
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/bioexplorer_python_sdk:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
