on:
  push:
    tags:
      - 1.*

jobs:
  bioexplorer_job:
    runs-on: ubuntu-latest
    name: BioExplorer
    steps:
    - uses: actions/checkout@v2
      name: Check out code
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
    - name: Use tag
      run: echo ${{steps.tag.outputs.tag}}
    - name: Login to DockerHub
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker Database
      uses: docker/build-push-action@v2
      with:
        context: ./storage/database
        push: true
        tags: ${{ secrets.DOCKERHUB_ORGANIZATION }}/bioexplorer-database:${{steps.tag.outputs.tag}}
    - name: Build and push Docker Back-end image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_ORGANIZATION }}/bioexplorer:${{steps.tag.outputs.tag}}
    - name: Build and push Docker Python SDK image
      uses: docker/build-push-action@v2
      with:
        context: ./bioexplorer/pythonsdk
        push: true
        tags: ${{ secrets.DOCKERHUB_ORGANIZATION }}/bioexplorer-python-sdk:${{steps.tag.outputs.tag}}
    - name: Build and push Docker User Interface
      uses: docker/build-push-action@v2
      with:
        context: ./bioexplorer/ui
        push: true
        tags: ${{ secrets.DOCKERHUB_ORGANIZATION }}/bioexplorer-ui:${{steps.tag.outputs.tag}}
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
