on:
  push:
    tags:
      - 1.*

jobs:
  bioexplorer_job:
    runs-on: ubuntu-latest
    name: BioExplorer
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
      name: Check out code
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build Python package
      run: |
        cd bioexplorer/pythonsdk
        python -m pip install --upgrade pip
        pip install --no-deps -r requirements_dev.txt    
        python setup.py sdist
    - name: Publish Python package to PyPI (test)
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_PASSWORD }}
        repository_url: https://upload.pypi.org/legacy/ 
        packages_dir: bioexplorer/pythonsdk/dist/
