- name: Publish BioExplorer to PyPI (test)
  uses: pypa/gh-action-pypi-publish@release/v1
  with:
    user: __token__
    password: ${{ secrets.PYPI_TEST_API_TOKEN }}
    repository_url: https://test.pypi.org/legacy/
